# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'default.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1127, 615)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(750, 560, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.add3 = QtWidgets.QToolButton(Dialog)
        self.add3.setGeometry(QtCore.QRect(750, 320, 31, 31))
        self.add3.setObjectName("add3")
        self.del3 = QtWidgets.QToolButton(Dialog)
        self.del3.setGeometry(QtCore.QRect(780, 320, 31, 31))
        self.del3.setObjectName("del3")
        self.select3 = QtWidgets.QPushButton(Dialog)
        self.select3.setGeometry(QtCore.QRect(660, 320, 61, 31))
        self.select3.setObjectName("select3")
        self.table1 = QtWidgets.QTableWidget(Dialog)
        self.table1.setGeometry(QtCore.QRect(0, 40, 221, 271))
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(2)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        self.select1 = QtWidgets.QPushButton(Dialog)
        self.select1.setGeometry(QtCore.QRect(80, 320, 61, 31))
        self.select1.setObjectName("select1")
        self.add1 = QtWidgets.QToolButton(Dialog)
        self.add1.setGeometry(QtCore.QRect(160, 320, 31, 31))
        self.add1.setObjectName("add1")
        self.del1 = QtWidgets.QToolButton(Dialog)
        self.del1.setGeometry(QtCore.QRect(190, 320, 31, 31))
        self.del1.setObjectName("del1")
        self.table3 = QtWidgets.QTableWidget(Dialog)
        self.table3.setGeometry(QtCore.QRect(590, 40, 221, 271))
        self.table3.setObjectName("table3")
        self.table3.setColumnCount(2)
        self.table3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(1, item)
        self.table2 = QtWidgets.QTableWidget(Dialog)
        self.table2.setGeometry(QtCore.QRect(290, 40, 221, 271))
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(2)
        self.table2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(1, item)
        self.select2 = QtWidgets.QPushButton(Dialog)
        self.select2.setGeometry(QtCore.QRect(350, 320, 61, 31))
        self.select2.setObjectName("select2")
        self.add2 = QtWidgets.QToolButton(Dialog)
        self.add2.setGeometry(QtCore.QRect(440, 320, 31, 31))
        self.add2.setObjectName("add2")
        self.del2 = QtWidgets.QToolButton(Dialog)
        self.del2.setGeometry(QtCore.QRect(470, 320, 31, 31))
        self.del2.setObjectName("del2")
        self.table4 = QtWidgets.QTableWidget(Dialog)
        self.table4.setGeometry(QtCore.QRect(880, 40, 221, 271))
        self.table4.setObjectName("table4")
        self.table4.setColumnCount(2)
        self.table4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(1, item)
        self.select4 = QtWidgets.QPushButton(Dialog)
        self.select4.setGeometry(QtCore.QRect(950, 320, 61, 31))
        self.select4.setObjectName("select4")
        self.add4 = QtWidgets.QToolButton(Dialog)
        self.add4.setGeometry(QtCore.QRect(1030, 320, 31, 31))
        self.add4.setObjectName("add4")
        self.del4 = QtWidgets.QToolButton(Dialog)
        self.del4.setGeometry(QtCore.QRect(1060, 320, 31, 31))
        self.del4.setObjectName("del4")
        self.pic = QtWidgets.QLabel(Dialog)
        self.pic.setGeometry(QtCore.QRect(20, 400, 331, 191))
        self.pic.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pic.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pic.setLineWidth(1)
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("../../../Downloads/14131077857079_former_shot.jpg"))
        self.pic.setAlignment(QtCore.Qt.AlignCenter)
        self.pic.setObjectName("pic")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add3.setText(_translate("Dialog", "+"))
        self.del3.setText(_translate("Dialog", "-"))
        self.select3.setText(_translate("Dialog", "选择"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "文件名"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "是否盖章"))
        self.select1.setText(_translate("Dialog", "选择"))
        self.add1.setText(_translate("Dialog", "+"))
        self.del1.setText(_translate("Dialog", "-"))
        item = self.table3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "文件名"))
        item = self.table3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "是否盖章"))
        item = self.table2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "文件名"))
        item = self.table2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "是否盖章"))
        self.select2.setText(_translate("Dialog", "选择"))
        self.add2.setText(_translate("Dialog", "+"))
        self.del2.setText(_translate("Dialog", "-"))
        item = self.table4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "文件名"))
        item = self.table4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "是否盖章"))
        self.select4.setText(_translate("Dialog", "选择"))
        self.add4.setText(_translate("Dialog", "+"))
        self.del4.setText(_translate("Dialog", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

